CREATE TABLE IF NOT EXISTS HOUSES (
    ID VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    BEDROOMS INTEGER,
    BATHROOMS INTEGER,
    AREA INTEGER,
    BUILD_DATE DATE,
    MARKET_PRICE DECIMAL,
    CURRENCY VARCHAR(10),
    ESTATE_AGENT VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    EMAIL VARCHAR(60),
    PASSWORD VARCHAR(60)
    );